# in compose.yaml

# version: "3.9"

services:
  db:
    image: postgres:15.2
    ports:
      - ${POSTGRES_PORT:-5432}
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgrespass

  web:
    image: ${WEB_IMAGE:-ghcr.io/sangche/kanban:latest}
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/postgres
      SECRET_KEY_BASE: i3GzcASR/ha2Ly0Gd4RskD/ucWN3+GSx6jkIPmaVtlVVBT0D0Tu3dRU5EZcOyhjI
      PHX_HOST: "localhost"
    ports:
      - 4000:4000
    command: >
      bash -c "dockerize -wait tcp://db:5432 -timeout 30s && bin/migrate && bin/server"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  db_data:

secrets:
  postgrespass:
    file: ./secrets/postgrespassfile