# in ci_cd.yaml

name: CI/CD Elixir

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Compile
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.18.2
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache directories(deps, _build)
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Get dependencies
        run: mix deps.get

      - name: Compile with warnings-as-errors
        run: mix compile --warnings-as-errors
